#!/usr/bin/env python3
# generate_inventory.py
# Reads our CSV inventory and writes hosts.yml

import csv

def read_inventory_csv(csv_file):
    """Read the master inventory CSV"""
    servers = []
    with open(csv_file, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            servers.append(row)
    return servers

def generate_inventory(servers, output_file):
    """Generate Ansible inventory YAML"""
    
    output = """# Generated inventory from master_inventory.csv
# Total servers: {count}
# Generated by generate_inventory.py

all:
  children:
"""
    
    # Group by building and room
    groups = {}
    for s in servers:
        key = f"{s['Building']}_{s['Room']}".lower().replace(' ', '_')
        if key not in groups:
            groups[key] = []
        groups[key].append(s)
    
    for group_name, group_servers in groups.items():
        output += f"\n  {group_name}:\n    hosts:\n"
        for s in group_servers[:10]:  # Sample first 10
            output += f"      {s['Hostname']}:\n"
            output += f"        ansible_host: {s['IP_Address']}\n"
        if len(group_servers) > 10:
            output += f"      # ... and {len(group_servers) - 10} more\n"
    
    with open(output_file, 'w') as f:
        f.write(output.format(count=len(servers)))
    
    print(f"Inventory written to {output_file}")
    print(f"Total servers: {len(servers)}")

if __name__ == "__main__":
    csv_file = "02_Infrastructure_Inventory/Servers/master_inventory.csv"
    output_file = "04_Ansible_Design/Inventory/auto_hosts.yml"
    
    servers = read_inventory_csv(csv_file)
    generate_inventory(servers, output_file)
